package com.FastFoodDelivery.service.Impl;

import com.FastFoodDelivery.dto.request.Drone.CreateDroneRequest;
import com.FastFoodDelivery.dto.request.Drone.UpdateDroneRequest;
import com.FastFoodDelivery.dto.response.Drone.DroneResponse;
import com.FastFoodDelivery.entity.Drone;
import com.FastFoodDelivery.exception.ResourceNotFoundException;
import com.FastFoodDelivery.repository.DroneRepository;
import com.FastFoodDelivery.service.DroneService;
import com.FastFoodDelivery.util.ValidationUtil;
import org.bson.types.ObjectId;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

@Service
public class DroneServiceImpl implements DroneService {

    @Autowired
    private DroneRepository droneRepository;

    @Autowired
    private ValidationUtil validationUtil;

    @Override
    public Page<DroneResponse> getAllDroneByRestaurantId(Pageable pageable, ObjectId restaurantId) {
        // Validate restaurant
        validationUtil.validateRestaurant(restaurantId);

        return droneRepository.findAllByRestaurantId(pageable, restaurantId)
                .map(DroneResponse::fromEntity);
    }

    @Override
    public DroneResponse getByDroneId(ObjectId droneId) {
        Drone drone = droneRepository.findById(droneId)
                .orElseThrow(() -> new ResourceNotFoundException("MenuItem", "id", droneId.toString()));
        return DroneResponse.fromEntity(drone);
    }

    @Override
    public DroneResponse createDrone(CreateDroneRequest request) {
        // Validate restaurant
        validationUtil.validateRestaurant(request.getRestaurantId());

        Drone drone = new Drone();
        // droneId will be auto-generated by MongoDB
        drone.setRestaurantId(request.getRestaurantId());
        drone.setModel(request.getModel());
        drone.setBattery(request.getBattery());
        drone.setCapacity(request.getCapacity());
        drone.setStatus("AVAILABLE");

        droneRepository.save(drone);

        return DroneResponse.fromEntity(drone);
    }

    @Override
    public DroneResponse updateDrone(UpdateDroneRequest request, ObjectId droneId) {
        Drone drone = droneRepository.findById(droneId)
                .orElseThrow(() -> new ResourceNotFoundException("MenuItem", "id", droneId.toString()));

        drone.setModel(request.getModel());
        drone.setBattery(request.getBattery());
        drone.setCapacity(request.getCapacity());
        drone.setStatus(request.getStatus());

        droneRepository.save(drone);

        return DroneResponse.fromEntity(drone);
    }

    @Override
    public void deleteDrone(ObjectId droneId) {
        Drone drone = droneRepository.findById(droneId)
                .orElseThrow(() -> new ResourceNotFoundException("MenuItem", "id", droneId.toString()));

        droneRepository.delete(drone);
    }

    @Override
    public void changeStatus(ObjectId droneId) {
        Drone drone = droneRepository.findById(droneId)
                .orElseThrow(() -> new ResourceNotFoundException("MenuItem", "id", droneId.toString()));

        if (drone.getStatus().equals("ACTIVE")){
            drone.setStatus("INACTIVE");
        } else if (drone.getStatus().equals("INACTIVE")){
            drone.setStatus("ACTIVE");
        }

        droneRepository.save(drone);
    }
}
